namespace BM25Engine.Tests;

public class PorterStemmerTests
{
    // Paper-worked-example pairs. The 1980 paper's tables illustrate each step in isolation
    // (e.g. the step-2 table shows "radicalli -> radical" as *just* the ALLI->AL substitution).
    // Running the full six-step pipeline on that same surface form can cascade into later steps
    // (e.g. "radical" also ends in "ical", so step 4/paper-step-3 further reduces it to "radic").
    // Expected values below are the verified full-pipeline output, cross-checked against
    // Porter's own official reference vocabulary (tartarus.org/martin/PorterStemmer/voc.txt +
    // output.txt) wherever a pair also appears there (e.g. troubled->troubl, agreed->agre,
    // rational->ration all match the official reference exactly), and hand-traced through
    // M()/Ends()/Step6 for the rest. See Stem_MatchesOfficialVocabularySample below for a
    // second, independently-sourced 87-pair suite pulled directly from that same official data.
    [Theory]
    // Step 1a
    [InlineData("caresses", "caress")]
    [InlineData("ponies", "poni")]
    [InlineData("ties", "ti")]
    [InlineData("caress", "caress")]
    [InlineData("cats", "cat")]
    // Step 1b
    [InlineData("feed", "feed")]
    [InlineData("agreed", "agre")]
    [InlineData("plastered", "plaster")]
    [InlineData("bled", "bled")]
    [InlineData("motoring", "motor")]
    [InlineData("sing", "sing")]
    [InlineData("conflated", "conflat")]
    [InlineData("troubled", "troubl")]
    [InlineData("sized", "size")]
    [InlineData("hopping", "hop")]
    [InlineData("tanned", "tan")]
    [InlineData("falling", "fall")]
    [InlineData("hissing", "hiss")]
    [InlineData("fizzed", "fizz")]
    [InlineData("failing", "fail")]
    [InlineData("filing", "file")]
    // Step 1c
    [InlineData("happy", "happi")]
    [InlineData("sky", "sky")]
    // Step 2 (paper's "step 2")
    [InlineData("relational", "relat")]
    [InlineData("conditional", "condit")]
    [InlineData("rational", "ration")]
    [InlineData("valenci", "valenc")]
    [InlineData("hesitanci", "hesit")]
    [InlineData("digitizer", "digit")]
    [InlineData("conformabli", "conform")]
    [InlineData("radicalli", "radic")]
    [InlineData("differentli", "differ")]
    [InlineData("vileli", "vile")]
    [InlineData("analogousli", "analog")]
    [InlineData("vietnamization", "vietnam")]
    [InlineData("predication", "predic")]
    [InlineData("operator", "oper")]
    [InlineData("feudalism", "feudal")]
    [InlineData("decisiveness", "decis")]
    [InlineData("hopefulness", "hope")]
    [InlineData("callousness", "callous")]
    [InlineData("formaliti", "formal")]
    [InlineData("sensitiviti", "sensit")]
    [InlineData("sensibiliti", "sensibl")]
    // Step 3 (paper's "step 3")
    [InlineData("triplicate", "triplic")]
    [InlineData("formative", "form")]
    [InlineData("formalize", "formal")]
    [InlineData("electriciti", "electr")]
    [InlineData("electrical", "electr")]
    [InlineData("hopeful", "hope")]
    [InlineData("goodness", "good")]
    // Step 4 (paper's "step 4")
    [InlineData("revival", "reviv")]
    [InlineData("allowance", "allow")]
    [InlineData("inference", "infer")]
    [InlineData("airliner", "airlin")]
    [InlineData("gyroscopic", "gyroscop")]
    [InlineData("adjustable", "adjust")]
    [InlineData("defensible", "defens")]
    [InlineData("irritant", "irrit")]
    [InlineData("replacement", "replac")]
    [InlineData("adjustment", "adjust")]
    [InlineData("dependent", "depend")]
    [InlineData("adoption", "adopt")]
    [InlineData("homologou", "homolog")]
    [InlineData("communism", "commun")]
    [InlineData("activate", "activ")]
    [InlineData("angulariti", "angular")]
    [InlineData("homologous", "homolog")]
    [InlineData("effective", "effect")]
    [InlineData("bowdlerize", "bowdler")]
    // Step 5a/5b (paper's "step 5")
    [InlineData("probate", "probat")]
    [InlineData("rate", "rate")]
    [InlineData("cease", "ceas")]
    [InlineData("controll", "control")]
    [InlineData("roll", "roll")]
    public void Stem_MatchesPorterPaperWorkedExample(string input, string expected)
    {
        var actual = PorterStemmer.Stem(input);
        Assert.Equal(expected, actual);
    }

    // Independent verification: 87 pairs pulled directly from Porter's own official reference
    // vocabulary (tartarus.org/martin/PorterStemmer/voc.txt + output.txt), evenly sampled from
    // the ~13,800 pairs where stemming actually changes the word. This corpus is the standard
    // conformance test used by essentially every Porter implementation.
    [Theory]
    [InlineData("abandoned", "abandon")]
    [InlineData("addle", "addl")]
    [InlineData("alcibiades", "alcibiad")]
    [InlineData("anticipates", "anticip")]
    [InlineData("arrived", "arriv")]
    [InlineData("austereness", "auster")]
    [InlineData("baths", "bath")]
    [InlineData("benefits", "benefit")]
    [InlineData("blois", "bloi")]
    [InlineData("breastplate", "breastplat")]
    [InlineData("buttocks", "buttock")]
    [InlineData("carthage", "carthag")]
    [InlineData("chariness", "chari")]
    [InlineData("claiming", "claim")]
    [InlineData("comedy", "comedi")]
    [InlineData("conclusions", "conclus")]
    [InlineData("constantly", "constantli")]
    [InlineData("correctioner", "correction")]
    [InlineData("credulity", "credul")]
    [InlineData("dally", "dalli")]
    [InlineData("defile", "defil")]
    [InlineData("desirers", "desir")]
    [InlineData("disaster", "disast")]
    [InlineData("dispraising", "disprais")]
    [InlineData("doubtful", "doubt")]
    [InlineData("easing", "eas")]
    [InlineData("endeared", "endear")]
    [InlineData("epileptic", "epilept")]
    [InlineData("exacting", "exact")]
    [InlineData("extravagant", "extravag")]
    [InlineData("fearfull", "fearful")]
    [InlineData("flatness", "flat")]
    [InlineData("forgetful", "forget")]
    [InlineData("furlongs", "furlong")]
    [InlineData("gilliams", "gilliam")]
    [InlineData("grappling", "grappl")]
    [InlineData("hammers", "hammer")]
    [InlineData("helping", "help")]
    [InlineData("hospitality", "hospit")]
    [InlineData("impasted", "impast")]
    [InlineData("indigne", "indign")]
    [InlineData("insisting", "insist")]
    [InlineData("isbels", "isbel")]
    [InlineData("kings", "king")]
    [InlineData("leaps", "leap")]
    [InlineData("living", "live")]
    [InlineData("magnificoes", "magnifico")]
    [InlineData("matters", "matter")]
    [InlineData("mille", "mill")]
    [InlineData("monarchy", "monarchi")]
    [InlineData("musty", "musti")]
    [InlineData("nodded", "nod")]
    [InlineData("offending", "offend")]
    [InlineData("outworths", "outworth")]
    [InlineData("particle", "particl")]
    [InlineData("perdurable", "perdur")]
    [InlineData("piercy", "pierci")]
    [InlineData("poets", "poet")]
    [InlineData("precedence", "preced")]
    [InlineData("privileged", "privileg")]
    [InlineData("proudly", "proudli")]
    [InlineData("questioning", "question")]
    [InlineData("recantation", "recant")]
    [InlineData("remembered", "rememb")]
    [InlineData("restitution", "restitut")]
    [InlineData("robustious", "robusti")]
    [InlineData("sanctified", "sanctifi")]
    [InlineData("scrolls", "scroll")]
    [InlineData("sexes", "sex")]
    [InlineData("sieve", "siev")]
    [InlineData("smiles", "smile")]
    [InlineData("speculation", "specul")]
    [InlineData("statues", "statu")]
    [InlineData("strossers", "strosser")]
    [InlineData("suppliants", "suppliant")]
    [InlineData("tainting", "taint")]
    [InlineData("thankings", "thank")]
    [InlineData("tolling", "toll")]
    [InlineData("tribunes", "tribun")]
    [InlineData("unattended", "unattend")]
    [InlineData("ungarter", "ungart")]
    [InlineData("unrelenting", "unrel")]
    [InlineData("urchins", "urchin")]
    [InlineData("vices", "vice")]
    [InlineData("warble", "warbl")]
    [InlineData("whitely", "white")]
    [InlineData("worths", "worth")]
    public void Stem_MatchesOfficialVocabularySample(string input, string expected)
    {
        var actual = PorterStemmer.Stem(input);
        Assert.Equal(expected, actual);
    }
}
